#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~ \
                    ~/code \
                    ~/code/photoassist \
                    ~/code/vidvox \
                    ~/code/meredithmonk \
                    ~/code/games/ \
                    ~/code/games/c \
                    ~/code/games/swift:metal \
                    -mindepth 1 -maxdepth 1 -type d \
                    2>/dev/null \
                    | fzf
              )
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)


# if callsite is not in TMUX and tmux is not running
# create a new session, attach to it, stop this program
if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

# if tmux doesnt already have a session with this name
# create one in detached mode (dont open it or nest it)
if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

 if [[ -z $TMUX ]]; then
     tmux attach-session -t $selected_name
 else
     tmux switch-client -t $selected_name
 fi

